## 버스 정류장
url="http://openapi.seoul.go.kr:8088/{key}/xml/CardBusStatisticsServiceNew/{startIndex}/{endIndex}/20151101/ "

## 교통 지점 데이터
url="http://openapi.seoul.go.kr:8088/{key}/xml/SpotInfo/{startIndex}/{endIndex}/"

## 지하철 역 정보
url="http://openAPI.seoul.go.kr:8088/{key}/xml/SearchLocationOfSTNByIDService/{startIndex}/{endIndex}/{stationNumber}/"

In [1]:
import urllib.request
from lxml import etree
from bs4 import BeautifulSoup
import requests
from urllib.request import urlopen
from xml.etree.ElementTree import parse
import pandas as pd

serviceKey="416b486a496b6861373365594b4642"
serviceKey2="704a534e596b686137354d61686e42"
url="http://openapi.seoul.go.kr:8088/{key}/xml/SpotInfo/{startIndex}/{endIndex}/"
#url="http://openapi.seoul.go.kr:8088/{key}/xml/CardBusStatisticsServiceNew/{startIndex}/{endIndex}/20151101/ "

In [2]:
urllib.request.urlopen(url.format(key=serviceKey, startIndex=1, endIndex=1000))

In [3]:
print(url.format(key=serviceKey2, startIndex=1001, endIndex=2000))

http://openapi.seoul.go.kr:8088/704a534e596b686137354d61686e42/xml/SpotInfo/1001/2000/

In [4]:
u=urlopen(url.format(key=serviceKey, startIndex=1, endIndex=1000))
doc=parse(u)

In [5]:
# Extract and output tags of interest

In [6]:
spot_num=[]
spot_nm=[]
grs80tm_x=[]
grs80tm_y=[]

In [7]:
#while endnumber<=1000:
url=url.format(key=serviceKey, startIndex=1, endIndex=1000)
req=requests.get(url)
html=req.text
soup=BeautifulSoup(html,'html.parser')

#print(soup)
spot_num=pd.Series(soup.find_all('spot_num'))
spot_nm=pd.Series(soup.find_all('spot_nm'))
grs80tm_x=pd.Series(soup.find_all('grs80tm_x'))
grs80tm_y=pd.Series(soup.find_all('grs80tm_y'))

idx=pd.Series(list(range(len(spot_num))))

In [8]:
nm=list(soup.find_all('spot_nm'))
temp=[]
for da in nm:
    temp.append((str(da).split("<spot_nm>"))[1].split("</spot_nm>")[0])

In [9]:
spot_nm=pd.Series(temp)
spot_nm

0                         성산로(금화터널)
1                         사직로(사직터널)
2                       자하문로(자하문터널)
3                        대사관로(삼청터널)
4                          율곡로(안국역)
5                     창경궁로(서울여자대학교)
6                    대학로(한국방송통신대학교)
7                          종로(동묘앞역)
8                          퇴계로(신당역)
9                        동호로(장충체육관)
10                      장충단로(장충단공원)
11                         퇴계로(회현역)
12                        세종대로(서울역)
13                    새문안로(서울역사박물관)
14                        종로(종로3가역)
15                        서소문로(시청역)
16                       세종대로(시청역2)
17                      을지로(을지로3가역)
18                         칠패로(숭례문)
19                           남산1호터널
20                           남산2호터널
21                           남산3호터널
22                         소월로(회현역)
23                     소파로(숭의여자대학교)
24                        도봉로(도봉산역)
25                       동일로(의정부IC)
26                        아차산로(워커힐)
27                       망우로(망우리공원)
28                      경춘북로(중랑경찰서)
29                        화랑로(조선왕릉)
                   ...
139         삼전로(잠실학원사거리-&gt;잠실트리지움)
140       삼학사로(서울놀이마당앞-&gt;석촌호(서호))
141              송파대로(석촌호수-&gt;석촌역)
142      송파대로(잠실대교남단-&gt;잠실대교남단교차로)
143        신천로(올림픽회관-&gt;잠실파크리오아파트)
144        신천로(잠실나루역-&gt;잠실대교남단교차로)
145        신천로(잠실나루역-&gt;잠실대교남단교차로)
146        신천로(잠실나루역-&gt;잠실파크리오아파트)
147        신천로(잠실대교남단교차로-&gt;잠실나루역)
148        신천로(잠실파크리오아파트-&gt;올림픽회관)
149            오금로(KT송파지사-&gt;송파구청)
150           오금로(방이삼거리-&gt;KT송파지사)
151             오금로(잠실나루역-&gt;송파구청)
152            올림픽로(송파구청-&gt;몽촌토성역)
153           올림픽로(올림픽회관-&gt;몽촌토성역)
154            올림픽로(잠실3사거리-&gt;신천역)
155            올림픽로(잠실역-&gt;잠실3사거리)
156             올림픽로(종합운동장-&gt;신천역)
157    올림픽로35가길(올림픽35가사거리-&gt;홈플러스)
158          잠실로(잠실3사거리-&gt;잠실트리지움)
159                           올림픽대로
160                            강변북로
161                           내부순환로
162                           북부간선로
163                          동부간선도로
164                          경부고속도로
165                           분당수서로
166                     강남순환로(관악터널)
167                          서부간선도로
168             잠실로(서울놀이마당앞~잠실트리지움)
Length: 169, dtype: object

In [10]:
nm=list(soup.find_all('spot_num'))
temp=[]
for da in nm:
    temp.append((str(da).split("<spot_num>"))[1].split("</spot_num>")[0])
    
spot_num=pd.Series(temp)
spot_num

0      A-01
1      A-02
2      A-03
3      A-04
4      A-05
5      A-06
6      A-07
7      A-08
8      A-09
9      A-10
10     A-11
11     A-12
12     A-13
13     A-14
14     A-15
15     A-16
16     A-17
17     A-18
18     A-19
19     A-20
20     A-21
21     A-22
22     A-23
23     A-24
24     B-01
25     B-02
26     B-03
27     B-04
28     B-05
29     B-06
       ...
139    D-58
140    D-59
141    D-60
142    D-61
143    D-62
144    D-63
145    D-64
146    D-65
147    D-66
148    D-67
149    D-68
150    D-69
151    D-70
152    D-71
153    D-72
154    D-73
155    D-74
156    D-75
157    D-76
158    D-77
159    F-01
160    F-02
161    F-03
162    F-04
163    F-05
164    F-06
165    F-07
166    F-08
167    F-09
168    Y-53
Length: 169, dtype: object

In [11]:
nm=list(soup.find_all('grs80tm_x'))
temp=[]
for da in nm:
    temp.append((str(da).split("<grs80tm_x>"))[1].split("</grs80tm_x>")[0])
    
grs80tm_x=pd.Series(temp)
grs80tm_x

0             195489
1      196756.776106
2      197216.855046
3      198648.893154
4      198645.671347
5       199825.89671
6      200185.014636
7      201515.783975
8      201850.055284
9      200633.487975
10            200410
11     197939.908023
12      197727.33407
13     197432.421007
14     199240.067506
15       197596.4694
16     197983.404032
17     199025.306571
18     197579.482653
19     200375.908853
20     199098.824842
21     198985.638133
22            197913
23            198564
24            203959
25     204889.526551
26     209697.184721
27     210241.085553
28     209331.347572
29            208764
           ...
139           208248
140           208599
141           209516
142           208691
143           209562
144           208650
145           209087
146           209556
147           209093
148           210122
149           209396
150           209508
151           209453
152           209677
153           209964
154           207537
155           208159
156           207593
157           209090
158           208246
159           197646
160           197729
161           199911
162           204649
163           207000
164           202107
165           207716
166           191832
167           189560
168           208208
Length: 169, dtype: object

In [12]:
nm=list(soup.find_all('grs80tm_y'))
temp=[]
for da in nm:
    temp.append((str(da).split("<grs80tm_y>"))[1].split("</grs80tm_y>")[0])
    
grs80tm_y=pd.Series(temp)
grs80tm_y

0             452136
1      452546.638644
2      454350.990432
3      455200.108465
4      452937.216603
5      453668.322568
6      453144.745427
7      452624.900832
8       451769.96985
9      451010.051429
10            450804
11     450888.928346
12     451006.009692
13     452243.292862
14     452288.413612
15     451463.528762
16     452006.746671
17     451837.790166
18     451141.212855
19     448730.787276
20     449434.634668
21     449446.700998
22            450842
23            450618
24            465826
25     465841.155869
26     450264.164859
27     455754.962803
28     457857.713789
29            459019
           ...
139           445668
140           445225
141           445092
142           446268
143           446649
144           446277
145           446505
146           446649
147           446493
148           446756
149           446247
150           446042
151           446200
152           446338
153           446415
154           445795
155           445839
156           445794
157           446501
158           445633
159           445188
160           446395
161           456580
162           456550
163           452742
164           443264
165           444241
166           437667
167           446828
168           445659
Length: 169, dtype: object

In [13]:
spot_num=pd.DataFrame(data={'spot_num':spot_num, 'index': idx},index=range(len(spot_num)))
spot_nm=pd.DataFrame(data={'spot_nm':spot_nm, 'index':idx}, index=range(len(spot_nm)))
grs80tm_x=pd.DataFrame(data={'grs80tm_x':grs80tm_x,'index':idx}, index=range(len(grs80tm_x)))
grs80tm_y=pd.DataFrame(data={'grs80tm_y':grs80tm_y,'index':idx}, index=range(len(grs80tm_y)))

In [14]:
print(spot_num.shape)
print(spot_nm.shape)
print(grs80tm_x.shape)
print(grs80tm_y.shape)

(169, 2)
(169, 2)
(169, 2)
(169, 2)

In [15]:
spot_num.head()

  spot_num  index
0     A-01      0
1     A-02      1
2     A-03      2
3     A-04      3
4     A-05      4

## Merging data

In [16]:
df=pd.merge(spot_num, spot_nm, how='left')
df=pd.merge(df,grs80tm_x, how='left')
df=pd.merge(df,grs80tm_y,how='left')
df

,spot_num,index,spot_nm,grs80tm_x,grs80tm_y
0,A-01,0,성산로(금화터널),195489,452136
1,A-02,1,사직로(사직터널),196756.776106,452546.638644
2,A-03,2,자하문로(자하문터널),197216.855046,454350.990432
3,A-04,3,대사관로(삼청터널),198648.893154,455200.108465
4,A-05,4,율곡로(안국역),198645.671347,452937.216603
5,A-06,5,창경궁로(서울여자대학교),199825.89671,453668.322568
6,A-07,6,대학로(한국방송통신대학교),200185.014636,453144.745427
7,A-08,7,종로(동묘앞역),201515.783975,452624.900832
8,A-09,8,퇴계로(신당역),201850.055284,451769.96985
9,A-10,9,동호로(장충체육관),200633.487975,451010.051429
10,A-11,10,장충단로(장충단공원),200410,450804
11,A-12,11,퇴계로(회현역),197939.908023,450888.928346
12,A-13,12,세종대로(서울역),197727.33407,451006.009692
13,A-14,13,새문안로(서울역사박물관),197432.421007,452243.292862
14,A-15,14,종로(종로3가역),199240.067506,452288.413612
15,A-16,15,서소문로(시청역),197596.4694,451463.528762
16,A-17,16,세종대로(시청역2),197983.404032,452006.746671
17,A-18,17,을지로(을지로3가역),199025.306571,451837.790166
18,A-19,18,칠패로(숭례문),197579.482653,451141.212855
19,A-20,19,남산1호터널,200375.908853,448730.787276
20,A-21,20,남산2호터널,199098.824842,449434.634668
21,A-22,21,남산3호터널,198985.638133,449446.700998
22,A-23,22,소월로(회현역),197913,450842
23,A-24,23,소파로(숭의여자대학교),198564,450618
24,B-01,24,도봉로(도봉산역),203959,465826
25,B-02,25,동일로(의정부IC),204889.526551,465841.155869
26,B-03,26,아차산로(워커힐),209697.184721,450264.164859
27,B-04,27,망우로(망우리공원),210241.085553,455754.962803
28,B-05,28,경춘북로(중랑경찰서),209331.347572,457857.713789
29,B-06,29,화랑로(조선왕릉),208764,459019
...,...,...,...,...,...
139,D-58,139,삼전로(잠실학원사거리-&gt;잠실트리지움),208248,445668
140,D-59,140,삼학사로(서울놀이마당앞-&gt;석촌호(서호)),208599,445225
141,D-60,141,송파대로(석촌호수-&gt;석촌역),209516,445092
142,D-61,142,송파대로(잠실대교남단-&gt;잠실대교남단교차로),208691,446268
143,D-62,143,신천로(올림픽회관-&gt;잠실파크리오아파트),209562,446649
144,D-63,144,신천로(잠실나루역-&gt;잠실대교남단교차로),208650,446277
145,D-64,145,신천로(잠실나루역-&gt;잠실대교남단교차로),209087,446505
146,D-65,146,신천로(잠실나루역-&gt;잠실파크리오아파트),209556,446649
147,D-66,147,신천로(잠실대교남단교차로-&gt;잠실나루역),209093,446493
148,D-67,148,신천로(잠실파크리오아파트-&gt;올림픽회관),210122,446756
149,D-68,149,오금로(KT송파지사-&gt;송파구청),209396,446247
150,D-69,150,오금로(방이삼거리-&gt;KT송파지사),209508,446042
151,D-70,151,오금로(잠실나루역-&gt;송파구청),209453,446200
152,D-71,152,올림픽로(송파구청-&gt;몽촌토성역),209677,446338
153,D-72,153,올림픽로(올림픽회관-&gt;몽촌토성역),209964,446415
154,D-73,154,올림픽로(잠실3사거리-&gt;신천역),207537,445795
155,D-74,155,올림픽로(잠실역-&gt;잠실3사거리),208159,445839
156,D-75,156,올림픽로(종합운동장-&gt;신천역),207593,445794
157,D-76,157,올림픽로35가길(올림픽35가사거리-&gt;홈플러스),209090,446501
158,D-77,158,잠실로(잠실3사거리-&gt;잠실트리지움),208246,445633
159,F-01,159,올림픽대로,197646,445188
160,F-02,160,강변북로,197729,446395
161,F-03,161,내부순환로,199911,456580
162,F-04,162,북부간선로,204649,456550
163,F-05,163,동부간선도로,207000,452742
164,F-06,164,경부고속도로,202107,443264
165,F-07,165,분당수서로,207716,444241
166,F-08,166,강남순환로(관악터널),191832,437667
167,F-09,167,서부간선도로,189560,446828
168,Y-53,168,잠실로(서울놀이마당앞~잠실트리지움),208208,445659

In [17]:
df.to_csv("spot_information.csv", encoding="ANSI")