In [1]:
import pandas as pd

In [4]:
busUser_info=pd.read_csv("data/버스 승하차인원데이터.csv", encoding="utf-8")

In [5]:
busStop=pd.read_csv("data/서울특별시 버스정류소 위치정보.csv", encoding="utf-8")

In [6]:
busUser_info[busUser_info['bus_sta_id']==1000]

Empty DataFrame
Columns: [Unnamed: 0, alight_pasgr_num, bus_route_id, bus_route_nm, bus_route_no, bus_sta_id, bus_sta_nm, ride_pasgr_num, stnd_bsst_id, use_dt]
Index: []

In [11]:
busUser_info

,Unnamed: 0,alight_pasgr_num,bus_route_id,bus_route_nm,bus_route_no,bus_sta_id,bus_sta_nm,ride_pasgr_num,stnd_bsst_id,use_dt
0,0,114,11110001,100번(하계동~용산구청),100,7197,명륜3가.성대입구,74,100000003,20180101
1,1,31,11110001,100번(하계동~용산구청),100,8839,을지로입구.로얄호텔,105,101000057,20180101
2,2,27,11110001,100번(하계동~용산구청),100,8864,을지로2가.파인에빈뉴,57,101000060,20180101
3,3,7,11110001,100번(하계동~용산구청),100,8878,서빙고역교차로,8,102000173,20180101
4,4,83,11110001,100번(하계동~용산구청),100,8881,을지로3가,20,101000061,20180101
5,5,16,11110001,100번(하계동~용산구청),100,8890,을지로3가,26,101000062,20180101
6,6,63,11110001,100번(하계동~용산구청),100,8935,을지로4가,14,101000063,20180101
7,7,65,11110001,100번(하계동~용산구청),100,8952,원남동,27,100000102,20180101
8,8,13,11110001,100번(하계동~용산구청),100,8984,을지로5가.중부시장,10,101000067,20180101
9,9,39,11110001,100번(하계동~용산구청),100,9038,을지로6가.국립중앙의료원,49,101000070,20180101
10,10,0,11110001,100번(하계동~용산구청),100,11084,서울시립북서울미술관,18,110000273,20180101
11,11,37,11110001,100번(하계동~용산구청),100,12869,월곡뉴타운,97,107000002,20180101
12,12,22,11110001,100번(하계동~용산구청),100,70555,중계시영3단지상가,145,110000279,20180101
13,13,13,11110001,100번(하계동~용산구청),100,70556,중계시영4단지,97,110000280,20180101
14,14,23,11110001,100번(하계동~용산구청),100,70561,하계우성아파트,243,110000353,20180101
15,15,20,11110001,100번(하계동~용산구청),100,70562,하계극동아파트,118,110000351,20180101
16,16,39,11110001,100번(하계동~용산구청),100,70563,월계헬스케어센터,98,110000238,20180101
17,17,131,11110001,100번(하계동~용산구청),100,70585,월계헬스케어센터,53,110000239,20180101
18,18,175,11110001,100번(하계동~용산구청),100,70586,하계시영아파트,27,110000352,20180101
19,19,99,11110001,100번(하계동~용산구청),100,70592,하계현대아파트,6,110000341,20180101
20,20,75,11110001,100번(하계동~용산구청),100,70593,노원구민체육센터,21,110000257,20180101
21,21,113,11110001,100번(하계동~용산구청),100,71196,삼선교.한성대학교,62,107000009,20180101
22,22,48,11110001,100번(하계동~용산구청),100,71198,창경궁.서울대학교병원,22,100000002,20180101
23,23,77,11110001,100번(하계동~용산구청),100,71205,삼선교.한성대학교,182,107000010,20180101
24,24,12,11110001,100번(하계동~용산구청),100,71430,중계역,0,110000265,20180101
25,25,1,11110001,100번(하계동~용산구청),100,71499,중계역,15,110000272,20180101
26,26,0,11110001,100번(하계동~용산구청),100,71598,노원평생학습관,11,110000286,20180101
27,27,8,11110001,100번(하계동~용산구청),100,71599,중계역2번출구,55,110000275,20180101
28,28,17,11110001,100번(하계동~용산구청),100,71600,중계3단지목련아파트,45,110000277,20180101
29,29,7,11110001,100번(하계동~용산구청),100,71601,노원경찰서,139,110000337,20180101
...,...,...,...,...,...,...,...,...,...,...
360994,970,121,11110013,142번(도봉동~고속터미널),142,9002130,서울중부기술교육원.블루스퀘어,92,102000066,20181231
360995,971,112,11110013,142번(도봉동~고속터미널),142,9002132,순천향대학병원,561,102000068,20181231
360996,972,320,11110013,142번(도봉동~고속터미널),142,9002133,한남5거리,178,102000072,20181231
360997,973,170,11110013,142번(도봉동~고속터미널),142,9002885,신당동.청구역,224,101000088,20181231
360998,974,239,11110013,142번(도봉동~고속터미널),142,9002886,신당동.청구역,152,101000087,20181231
360999,975,239,11110013,142번(도봉동~고속터미널),142,9002887,약수역2번출구.중구구립도서관,157,101000089,20181231
361000,976,179,11110013,142번(도봉동~고속터미널),142,9002888,약수역3번출구.약수하이츠,358,101000090,20181231
361001,977,74,11110013,142번(도봉동~고속터미널),142,9003149,장충단로입구,17,102000064,20181231
361002,978,147,11110013,142번(도봉동~고속터미널),142,9006333,신사역,310,121000016,20181231
361003,979,561,11110013,142번(도봉동~고속터미널),142,9034223,순천향대학병원.한남오거리,468,102000071,20181231
361004,980,109,11110013,142번(도봉동~고속터미널),142,9035991,송도병원앞,92,101000096,20181231
361005,981,256,11110014,143번(정릉~개포동),143,7197,명륜3가.성대입구,385,100000003,20181231
361006,982,238,11110014,143번(정릉~개포동),143,7646,정릉길음시장,848,107000031,20181231
361007,983,283,11110014,143번(정릉~개포동),143,8952,원남동,228,100000102,20181231
361008,984,9,11110014,143번(정릉~개포동),143,9008,정릉산장아파트,850,107000071,20181231
361009,985,81,11110014,143번(정릉~개포동),143,9037,정릉4동주민센터.경국사,183,107000073,20181231
361010,986,151,11110014,143번(정릉~개포동),143,9044,정릉4동주민센터.경국사,9,107000074,20181231
361011,987,449,11110014,143번(정릉~개포동),143,9052,뉴코아아울렛,592,121000131,20181231
361012,988,380,11110014,143번(정릉~개포동),143,9056,신반포자이아파트,399,121000132,20181231
361013,989,112,11110014,143번(정릉~개포동),143,9061,KEB하나은행정릉중앙지점,437,107000075,20181231
361014,990,260,11110014,143번(정릉~개포동),143,9073,KEB하나은행정릉중앙지점,62,107000076,20181231
361015,991,150,11110014,143번(정릉~개포동),143,9104,정릉우체국앞,558,107000079,20181231
361016,992,291,11110014,143번(정릉~개포동),143,9204,숭덕초교,145,107000030,20181231
361017,993,208,11110014,143번(정릉~개포동),143,10843,영동교입구.청담자이아파트,167,122000066,20181231
361018,994,146,11110014,143번(정릉~개포동),143,10864,우리은행청담지점.청담삼익아파트,202,122000069,20181231
361019,995,236,11110014,143번(정릉~개포동),143,10979,은마파출소,795,122000131,20181231
361020,996,663,11110014,143번(정릉~개포동),143,10985,휘문중고등학교,215,122000146,20181231
361021,997,295,11110014,143번(정릉~개포동),143,11029,삼성역,752,122000330,20181231
361022,998,106,11110014,143번(정릉~개포동),143,13715,시립개포도서관,1,122000349,20181231
361023,999,181,11110014,143번(정릉~개포동),143,70488,신반포13차아파트,161,121000103,20181231

In [18]:
busStop[busStop['정류소명']=="서빙고역교차로"]

     정류소번호     정류소명         X좌표        Y좌표
746   3267  서빙고역교차로  126.990092  37.520426

In [19]:
busUser_info=busUser_info[['alight_pasgr_num','bus_sta_nm','ride_pasgr_num','use_dt']]

In [20]:
busUser_info.shape

(361024, 4)

In [22]:
busUser_info['lati']=0 # Y좌표값
busUser_info['long']=0 # X좌표값

C:\Users\B-17\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\B-17\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [27]:
busUser_info.head(10)

   alight_pasgr_num     bus_sta_nm  ride_pasgr_num    use_dt  lati  long
0               114      명륜3가.성대입구              74  20180101     0     0
1                31     을지로입구.로얄호텔             105  20180101     0     0
2                27    을지로2가.파인에빈뉴              57  20180101     0     0
3                 7        서빙고역교차로               8  20180101     0     0
4                83          을지로3가              20  20180101     0     0
5                16          을지로3가              26  20180101     0     0
6                63          을지로4가              14  20180101     0     0
7                65            원남동              27  20180101     0     0
8                13     을지로5가.중부시장              10  20180101     0     0
9                39  을지로6가.국립중앙의료원              49  20180101     0     0

In [35]:
busUser_info.shape[0]

361024

In [43]:
for i in range(0,int(busUser_info.shape[0]/1000)):
    #print("좌ㅠㅛ!!",busStop[busStop['정류소명']==busUser_info.iloc[i]['bus_sta_nm']]['Y좌표'])
    if len(busStop[busStop['정류소명']==busUser_info.iloc[i]['bus_sta_nm']]['Y좌표'])> 0:
        print(busStop[busStop['정류소명']==busUser_info.iloc[i]['bus_sta_nm']]['Y좌표'].iloc[0])
    #busUser_info.iloc[i]['long']=busStop[busStop['정류소명']==busUser_info.iloc[i]['bus_sta_nm']]['X좌표']

37.5826711749
37.5658757422
37.5204258449
37.5663556351
37.5663556351
37.5666470197
37.5745325055
37.5666200422
37.5660747142
37.640586005799996
37.6069061871
37.6468582175
37.6435314138
37.6352513689
37.6338991064
37.631969768400005
37.631969768400005
37.6339842413
37.6449579802
37.6477683703
37.5898525089
37.5791830159
37.5898525089
37.644256969299995
37.644256969299995
37.6393428578
37.6456175479
37.6475000013
37.641792753699995
37.6404263202
37.6383654607
37.6365715509
37.6279837976
37.6261891646
37.6234130879
37.6203171059
37.6137499056
37.6117546845
37.6101518086
37.6069061871
37.6036262275
37.6036262275
37.6099346062
37.611782602699996
37.6136786234
37.6178525754
37.6203171059
37.623465954299995
37.6251552305
37.629037896
37.6363150439
37.63813
37.6393648263
37.6420899031
37.6009238115
37.646094866700004
37.639204879
37.5988112954
37.5937432794
37.5937432794
37.5988112954
37.5694963125
37.565824354200004
37.578043
37.5811194873
37.5845697705
37.5633219814
37.562884999999994
37.566246226
37.5302839538
37.525474865
37.5302839538
37.586242999999996
37.525474865
37.5226191604
37.5586388574
37.63813
37.63813
37.5200094838
37.634078815
37.5211711184
37.6208649775
37.6378760581
37.561175
37.5215067914
37.5212059729
37.520656299
37.5200771209
37.5197783418
37.5197783418
37.5188201813
37.5183400338
37.5180656216
37.517704332
37.5179148687
37.572879013299996
37.5664010399
37.56451
37.5745
37.5650528273
37.5679608485
37.5705596025
37.5550251461
37.550975599299996
37.550975599299996
37.543295633
37.543295633
37.5352698987
37.5352698987
37.5314970129
37.5314970129
37.527293
37.5240898013
37.5240898013
37.5179148687
37.5214756887
37.5200094838
37.527293
37.5550251461
37.6572118702
37.6580003804
37.6488174173
37.599228255
37.6526308865
37.6571614212
37.6571614212
37.563206740700004
37.5719529259
37.6574593323
37.6574593323
37.6572118702
37.6452929962
37.6545598452
37.6488174173
37.6452929962
37.6412417798
37.6366590882
37.6374887513
37.6014326326
37.599228255
37.5948052663
37.588563685100006
37.5855475535
37.5824024531
37.5797066498
37.5759288312
37.5797777214
37.5824024531
37.5855475535
37.5881473927
37.594396924499996
37.6014326326
37.6631049128
37.660768287399996
37.6137621245
37.6058827177
37.6058827177
37.660768287399996
37.658907
37.6573507894
37.6574046264
37.6576477672
37.6580029761
37.658188686399996
37.6576477672
37.657656
37.6573507894
37.619714091300004
37.6248696784
37.6312262117
37.6631049128
37.6412417798
37.6545598452
37.6137621245
37.570023
37.5737255179
37.5737255179
37.6578002243
37.5652819605
37.6312262117
37.6248696784
37.619714091300004
37.6384770489
37.568145926999996
37.5766303332
37.5701184824
37.5701386788
37.5705069968
37.570756793
37.5709624756
37.572302321900004
37.5709624756
37.570756793
37.5705069968
37.5701386788
37.5701184824
37.570135474000004
37.5683632936
37.5826711749
37.6440304124
37.649637244000004
37.656087
37.657568074400004
37.657568074400004
37.6069061871
37.5898525089
37.5791830159
37.5898525089
37.6520957586
37.6471279991
37.6480182386
37.6507752318
37.65318414
37.6069061871
37.6036262275
37.6036262275
37.5988112954
37.5937432794
37.5937432794
37.5988112954
37.578043
37.5811194873
37.5845697705
37.6137621245
37.619714091300004
37.6248696784
37.6312262117
37.644960075300006
37.6457412104
37.6457412104
37.644960075300006
37.586242999999996
37.6453394473
37.6451811712
37.6440304124
37.6415355739
37.6376252025
37.636181397899996
37.6353812772
37.6351433469
37.6346136086
37.6346136086
37.6351433469
37.6353812772
37.636181397899996
37.6376252025
37.6415355739
37.6451811712
37.6460641437
37.6390783287
37.6388467098
37.659587202800004
37.6137621245
37.656202
37.5717262368
37.6312262117
37.6248696784
37.619714091300004
37.572879013299996
37.5745
37.575873
37.576119355
37.5740223509
37.5826711749
37.6115318739
37.5745325055
37.6456469297
37.6456469297
37.6467731414
37.6467731414
37.5898525089
37.5791830159
37.5898525089
37.6036262275
37.5988112954
37.5937432794
37.5937432794
37.5988112954
37.5612168046
37.6450333774
37.636508929899996
37.6333403549
37.629858846
37.6252947897
37.623073214899996
37.6216450698
37.618088303600004
37.6154596915
37.6115318739
37.607838082600004
37.5694963125
37.561223292600005
37.562380405700004
37.565824354200004
37.578043
37.5811194873
37.5845697705
37.6018744304
37.607838082600004
37.618088303600004
37.6216450698
37.623073214899996
37.6252947897
37.629858846
37.6333403549
37.636508929899996
37.6450333774
37.6491109904
37.586242999999996
37.6418977929
37.6418977929
37.6491109904
37.5608934844
37.6154596915
37.6462100417
37.6462100417
37.5606538896
37.5619180947
37.5612168046
37.558267523699996
37.558267523699996
37.558771309099996
37.572879013299996
37.564774595100005
37.5745
37.5679608485
37.5705596025
37.5550251461
37.5761500409
37.5876921711
37.5658757422
37.5663556351
37.5666200422
37.5660747142
37.5719529259
37.6603435605
37.6574468479
37.6574468479
37.649637244000004
37.6607333963
37.640586005799996
37.6393911575
37.6365715509
37.634078815
37.6152702687
37.6071323536
37.5990762154
37.6365715509
37.6348491458

In [56]:
busUser_info['lati'].iloc[0]=1000

C:\Users\B-17\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\B-17\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

# 정류소 X, Y좌표 정보 저장

In [63]:
stopName_XY={}
for i in range(busStop.shape[0]):
    li=[]
    stopName_XY[busStop['정류소명'].iloc[i]]=busStop[['Y좌표','X좌표']].iloc[i]

In [65]:
len(stopName_XY)

6728

In [75]:
stopName_XY.values()

dict_values([Y좌표     37.569765
X좌표    126.987750
Name: 0, dtype: float64, Y좌표     37.578828
X좌표    126.996872
Name: 115, dtype: float64, Y좌표     37.582671
X좌표    126.998340
Name: 2, dtype: float64, Y좌표     37.568579
X좌표    126.987613
Name: 3, dtype: float64, Y좌표     37.585920
X좌표    127.001003
Name: 335, dtype: float64, Y좌표     37.565579
X좌표    126.966565
Name: 4900, dtype: float64, Y좌표     37.569412
X좌표    126.970609
Name: 7, dtype: float64, Y좌표     37.568759
X좌표    126.976762
Name: 562, dtype: float64, Y좌표     37.569954
X좌표    126.980826
Name: 277, dtype: float64, Y좌표     37.569969
X좌표    126.985575
Name: 278, dtype: float64, Y좌표     37.570361
X좌표    126.989988
Name: 15, dtype: float64, Y좌표     37.570627
X좌표    126.995284
Name: 17, dtype: float64, Y좌표     37.570881
X좌표    126.999335
Name: 19, dtype: float64, Y좌표     37.571127
X좌표    127.005714
Name: 21, dtype: float64, Y좌표     37.572302
X좌표    127.013451
Name: 22, dtype: float64, Y좌표     37.571953
X좌표    127.012046
Name: 23, dtype: float64, Y좌표     37.573729
X좌표    127.017816
Name: 128, dtype: float64, Y좌표     37.587191
X좌표    126.969770
Name: 28, dtype: float64, Y좌표     37.583266
X좌표    126.970265
Name: 27, dtype: float64, Y좌표     37.584966
X좌표    126.971155
Name: 34, dtype: float64, Y좌표     37.588129
X좌표    126.972461
Name: 33, dtype: float64, Y좌표     37.592335
X좌표    126.967191
Name: 32, dtype: float64, Y좌표     37.580513
X좌표    126.971385
Name: 36, dtype: float64, Y좌표     37.583091
X좌표    126.970621
Name: 37, dtype: float64, Y좌표     37.574855
X좌표    126.968189
Name: 49, dtype: float64, Y좌표     37.576221
X좌표    126.968904
Name: 303, dtype: float64, Y좌표     37.575755
X좌표    126.971316
Name: 285, dtype: float64, Y좌표     37.576950
X좌표    126.979338
Name: 205, dtype: float64, Y좌표     37.572406
X좌표    126.977319
Name: 43, dtype: float64, Y좌표     37.570023
X좌표    126.971248
Name: 45, dtype: float64, Y좌표     37.572231
X좌표    126.976565
Name: 378, dtype: float64, Y좌표     37.575745
X좌표    126.971484
Name: 48, dtype: float64, Y좌표     37.569451
X좌표    126.976546
Name: 50, dtype: float64, Y좌표     37.575726
X좌표    126.981969
Name: 51, dtype: float64, Y좌표     37.576338
X좌표    126.984829
Name: 152, dtype: float64, Y좌표     37.604719
X좌표    126.961209
Name: 66, dtype: float64, Y좌표     37.602268
X좌표    126.961433
Name: 65, dtype: float64, Y좌표     37.600552
X좌표    126.958934
Name: 64, dtype: float64, Y좌표     37.599854
X좌표    126.957402
Name: 340, dtype: float64, Y좌표     37.597685
X좌표    126.962966
Name: 329, dtype: float64, Y좌표     37.595558
X좌표    126.963978
Name: 61, dtype: float64, Y좌표     37.592935
X좌표    126.963768
Name: 318, dtype: float64, Y좌표     37.599444
X좌표    126.959792
Name: 144, dtype: float64, Y좌표     37.611480
X좌표    126.956482
Name: 73, dtype: float64, Y좌표     37.609682
X좌표    126.956622
Name: 129, dtype: float64, Y좌표     37.60861
X좌표    126.95621
Name: 69, dtype: float64, Y좌표     37.608305
X좌표    126.956417
Name: 70, dtype: float64, Y좌표     37.607009
X좌표    126.959102
Name: 72, dtype: float64, Y좌표     37.604371
X좌표    126.963535
Name: 74, dtype: float64, Y좌표     37.605322
X좌표    126.966043
Name: 75, dtype: float64, Y좌표     37.605681
X좌표    126.966817
Name: 154, dtype: float64, Y좌표     37.608766
X좌표    126.972999
Name: 77, dtype: float64, Y좌표     37.502804
X좌표    126.884927
Name: 6964, dtype: float64, Y좌표     37.608190
X좌표    126.972797
Name: 80, dtype: float64, Y좌표     37.606517
X좌표    126.970000
Name: 81, dtype: float64, Y좌표     37.605779
X좌표    126.967628
Name: 82, dtype: float64, Y좌표     37.604859
X좌표    126.965687
Name: 364, dtype: float64, Y좌표     37.568532
X좌표    126.968338
Name: 343, dtype: float64, Y좌표     37.575515
X좌표    126.956292
Name: 5023, dtype: float64, Y좌표     37.568254
X좌표    126.964527
Name: 86, dtype: float64, Y좌표     37.567108
X좌표    126.967588
Name: 87, dtype: float64, Y좌표     37.571482
X좌표    126.959373
Name: 5301, dtype: float64, Y좌표     37.577195
X좌표    126.987878
Name: 97, dtype: float64, Y좌표     37.569242
X좌표    126.980268
Name: 90, dtype: float64, Y좌표     37.568462
X좌표    126.983625
Name: 494, dtype: float64, Y좌표     37.568437
X좌표    126.990674
Name: 92, dtype: float64, Y좌표     37.568869
X좌표    126.996491
Name: 93, dtype: float64, Y좌표     37.569451
X좌표    126.999797
Name: 94, dtype: float64, Y좌표     37.574533
X좌표    126.997338
Name: 96, dtype: float64, Y좌표     37.573865
X좌표    126.983120
Name: 375, dtype: float64, Y좌표     37.574611
X좌표    126.982720
Name: 101, dtype: float64, Y좌표     37.57450
X좌표    127.00223
Name: 102, dtype: float64, Y좌표     37.572879
X좌표    127.002144
Name: 103, dtype: float64, Y좌표     37.570560
X좌표    127.002183
Name: 104, dtype: float64, Y좌표     37.569835
X좌표    127.002849
Name: 105, dtype: float64, Y좌표     37.571726
X좌표    127.008413
Name: 106, dtype: float64, Y좌표     37.574460
X좌표    127.006343
Name: 108, dtype: float64, Y좌표     37.575873
X좌표    127.000533
Name: 109, dtype: float64, Y좌표     37.578130
X좌표    127.001994
Name: 113, dtype: float64, Y좌표     37.581119
X좌표    127.002277
Name: 111, dtype: float64, Y좌표     37.581064
X좌표    127.001940
Name: 112, dtype: float64, Y좌표     37.576257
X좌표    127.002955
Name: 141, dtype: float64, Y좌표     37.585765
X좌표    127.000725
Name: 117, dtype: float64, Y좌표     37.583333
X좌표    126.999399
Name: 118, dtype: float64, Y좌표     37.584023
X좌표    127.001328
Name: 119, dtype: float64, Y좌표     37.584570
X좌표    127.001718
Name: 120, dtype: float64, Y좌표     37.574093
X좌표    127.015556
Name: 121, dtype: float64, Y좌표     37.571898
X좌표    127.015888
Name: 123, dtype: float64, Y좌표     37.578413
X좌표    127.015178
Name: 124, dtype: float64, Y좌표     37.578772
X좌표    127.015549
Name: 125, dtype: float64, Y좌표     37.574180
X좌표    127.015802
Name: 126, dtype: float64, Y좌표     37.575929
X좌표    127.022780
Name: 127, dtype: float64, Y좌표     37.569496
X좌표    126.997744
Name: 130, dtype: float64, Y좌표     37.572581
X좌표    126.997479
Name: 131, dtype: float64, Y좌표     37.569900
X좌표    126.972132
Name: 132, dtype: float64, Y좌표     37.568689
X좌표    126.993779
Name: 133, dtype: float64, Y좌표     37.569930
X좌표    127.008038
Name: 134, dtype: float64, Y좌표     37.569998
X좌표    127.012955
Name: 135, dtype: float64, Y좌표     37.570651
X좌표    127.018825
Name: 500, dtype: float64, Y좌표     37.575829
X좌표    126.996833
Name: 137, dtype: float64, Y좌표     37.574272
X좌표    127.020437
Name: 138, dtype: float64, Y좌표     37.601620
X좌표    126.955021
Name: 142, dtype: float64, Y좌표     37.613050
X좌표    126.955888
Name: 143, dtype: float64, Y좌표     37.572417
X좌표    127.006591
Name: 146, dtype: float64, Y좌표     37.574386
X좌표    127.023118
Name: 147, dtype: float64, Y좌표     37.56784
X좌표    126.98853
Name: 495, dtype: float64, Y좌표     37.572131
X좌표    127.022787
Name: 149, dtype: float64, Y좌표     37.610967
X좌표    126.978368
Name: 150, dtype: float64, Y좌표     37.577477
X좌표    126.988900
Name: 288, dtype: float64, Y좌표     37.588228
X좌표    126.981647
Name: 155, dtype: float64, Y좌표     37.582079
X좌표    126.964247
Name: 156, dtype: float64, Y좌표     37.590948
X좌표    126.992864
Name: 157, dtype: float64, Y좌표     37.587653
X좌표    126.996705
Name: 158, dtype: float64, Y좌표     37.566416
X좌표    126.966218
Name: 159, dtype: float64, Y좌표     37.580404
X좌표    127.008722
Name: 160, dtype: float64, Y좌표     37.482549
X좌표    126.987485
Name: 9474, dtype: float64, Y좌표     37.604981
X좌표    126.965201
Name: 167, dtype: float64, Y좌표     37.585878
X좌표    126.981848
Name: 306, dtype: float64, Y좌표     37.580997
X좌표    126.966603
Name: 164, dtype: float64, Y좌표     37.590255
X좌표    126.993408
Name: 359, dtype: float64, Y좌표     37.589074
X좌표    126.997141
Name: 350, dtype: float64, Y좌표     37.567530
X좌표    126.965227
Name: 168, dtype: float64, Y좌표     37.589258
X좌표    126.989632
Name: 169, dtype: float64, Y좌표     37.582660
X좌표    126.989371
Name: 170, dtype: float64, Y좌표     37.604252
X좌표    126.961491
Name: 171, dtype: float64, Y좌표     37.584685
X좌표    126.982211
Name: 300, dtype: float64, Y좌표     37.580335
X좌표    126.968750
Name: 293, dtype: float64, Y좌표     37.589768
X좌표    126.993769
Name: 357, dtype: float64, Y좌표     37.589628
X좌표    126.999314
Name: 346, dtype: float64, Y좌표     37.488742
X좌표    126.997037
Name: 9626, dtype: float64, Y좌표     37.568787
X좌표    126.964069
Name: 177, dtype: float64, Y좌표     37.581396
X좌표    127.012735
Name: 2905, dtype: float64, Y좌표     37.587531
X좌표    126.986107
Name: 349, dtype: float64, Y좌표     37.583081
X좌표    126.987809
Name: 180, dtype: float64, Y좌표     37.606980
X좌표    126.959186
Name: 181, dtype: float64, Y좌표     37.571747
X좌표    126.997541
Name: 182, dtype: float64, Y좌표     37.581645
X좌표    126.981326
Name: 292, dtype: float64, Y좌표     37.588725
X좌표    126.995231
Name: 355, dtype: float64, Y좌표     37.587389
X좌표    126.999991
Name: 341, dtype: float64, Y좌표     37.607980
X좌표    126.962431
Name: 187, dtype: float64, Y좌표     37.570299
X좌표    126.961941
Name: 4919, dtype: float64, Y좌표     37.582259
X좌표    127.014599
Name: 2899, dtype: float64, Y좌표     37.586266
X좌표    126.985562
Name: 345, dtype: float64, Y좌표     37.583092
X좌표    126.986965
Name: 191, dtype: float64, Y좌표     37.607928
X좌표    126.957744
Name: 192, dtype: float64, Y좌표     37.570635
X좌표    126.993331
Name: 193, dtype: float64, Y좌표     37.579255
X좌표    126.979553
Name: 194, dtype: float64, Y좌표     37.588722
X좌표    126.912369
Name: 4573, dtype: float64, Y좌표     37.451210
X좌표    126.910523
Name: 7570, dtype: float64, Y좌표     37.586038
X좌표    127.000614
Name: 197, dtype: float64, Y좌표     37.608954
X좌표    126.963792
Name: 198, dtype: float64, Y좌표     37.570702
X좌표    126.962115
Name: 199, dtype: float64, Y좌표     37.581898
X좌표    127.016235
Name: 348, dtype: float64, Y좌표     37.584106
X좌표    126.985031
Name: 201, dtype: float64, Y좌표     37.582743
X좌표    126.985221
Name: 333, dtype: float64, Y좌표     37.610752
X좌표    126.945775
Name: 4510, dtype: float64, Y좌표     37.571073
X좌표    126.992181
Name: 204, dtype: float64, Y좌표     37.611277
X좌표    126.964110
Name: 207, dtype: float64, Y좌표     37.572878
X좌표    126.959745
Name: 208, dtype: float64, Y좌표     37.579785
X좌표    127.017151
Name: 344, dtype: float64, Y좌표     37.581281
X좌표    126.985169
Name: 328, dtype: float64, Y좌표     37.606699
X좌표    126.958756
Name: 362, dtype: float64, Y좌표     37.581216
X좌표    127.001921
Name: 214, dtype: float64, Y좌표     37.612010
X좌표    126.965464
Name: 215, dtype: float64, Y좌표     37.573847
X좌표    126.960721
Name: 216, dtype: float64, Y좌표     37.580353
X좌표    127.015693
Name: 217, dtype: float64, Y좌표     37.579943
X좌표    126.985129
Name: 322, dtype: float64, Y좌표     37.482898
X좌표    126.988631
Name: 9463, dtype: float64, Y좌표     37.576237
X좌표    126.997511
Name: 220, dtype: float64, Y좌표     37.613483
X좌표    126.965779
Name: 221, dtype: float64, Y좌표     37.574648
X좌표    126.961860
Name: 222, dtype: float64, Y좌표     37.580511
X좌표    127.014964
Name: 223, dtype: float64, Y좌표     37.578899
X좌표    126.985022
Name: 224, dtype: float64, Y좌표     37.605284
X좌표    126.957578
Name: 360, dtype: float64, Y좌표     37.576948
X좌표    127.002008
Name: 372, dtype: float64, Y좌표     37.614310
X좌표    126.967687
Name: 227, dtype: float64, Y좌표     37.576306
X좌표    126.962001
Name: 228, dtype: float64, Y좌표     37.577558
X좌표    126.985676
Name: 229, dtype: float64, Y좌표     37.604610
X좌표    126.956984
Name: 230, dtype: float64, Y좌표     37.578119
X좌표    126.999503
Name: 231, dtype: float64, Y좌표     37.577567
X좌표    127.002479
Name: 232, dtype: float64, Y좌표     37.612935
X좌표    126.968539
Name: 233, dtype: float64, Y좌표     37.614686
X좌표    126.999738
Name: 2924, dtype: float64, Y좌표     37.576903
X좌표    127.015389
Name: 235, dtype: float64, Y좌표     37.575160
X좌표    126.986517
Name: 236, dtype: float64, Y좌표     37.604072
X좌표    126.957463
Name: 358, dtype: float64, Y좌표     37.581148
X좌표    127.002257
Name: 238, dtype: float64, Y좌표     37.611606
X좌표    126.969021
Name: 239, dtype: float64, Y좌표     37.573976
X좌표    126.963445
Name: 240, dtype: float64, Y좌표     37.573678
X좌표    126.987292
Name: 241, dtype: float64, Y좌표     37.603340
X좌표    126.957667
Name: 356, dtype: float64, Y좌표     37.580555
X좌표    126.997431
Name: 243, dtype: float64, Y좌표     37.583454
X좌표    127.001941
Name: 244, dtype: float64, Y좌표     37.612406
X좌표    126.969948
Name: 245, dtype: float64, Y좌표     37.573633
X좌표    126.964143
Name: 246, dtype: float64, Y좌표     37.572694
X좌표    127.014245
Name: 247, dtype: float64, Y좌표     37.570545
X좌표    126.987438
Name: 248, dtype: float64, Y좌표     37.601864
X좌표    126.957948
Name: 354, dtype: float64, Y좌표     37.583308
X좌표    126.999366
Name: 250, dtype: float64, Y좌표     37.571902
X좌표    126.977317
Name: 251, dtype: float64, Y좌표     37.613406
X좌표    126.970701
Name: 252, dtype: float64, Y좌표     37.574647
X좌표    126.964626
Name: 253, dtype: float64, Y좌표     37.572049
X좌표    127.011722
Name: 254, dtype: float64, Y좌표     37.570339
X좌표    126.985071
Name: 255, dtype: float64, Y좌표     37.601989
X좌표    126.957155
Name: 256, dtype: float64, Y좌표     37.577072
X좌표    126.972473
Name: 257, dtype: float64, Y좌표     37.576126
X좌표    127.000745
Name: 258, dtype: float64, Y좌표     37.583588
X좌표    126.999703
Name: 289, dtype: float64, Y좌표     37.613900
X좌표    126.971846
Name: 260, dtype: float64, Y좌표     37.575560
X좌표    126.965318
Name: 261, dtype: float64, Y좌표     37.571176
X좌표    127.006140
Name: 262, dtype: float64, Y좌표     37.647963
X좌표    127.067940
Name: 4071, dtype: float64, Y좌표     37.576588
X좌표    126.979665
Name: 264, dtype: float64, Y좌표     37.579493
X좌표    126.971028
Name: 265, dtype: float64, Y좌표     37.588464
X좌표    126.990004
Name: 369, dtype: float64, Y좌표     37.614572
X좌표    126.974121
Name: 267, dtype: float64, Y좌표     37.576813
X좌표    126.965329
Name: 268, dtype: float64, Y좌표     37.571419
X좌표    127.002090
Name: 269, dtype: float64, Y좌표     37.571947
X좌표    126.983297
Name: 270, dtype: float64, Y좌표     37.580192
X좌표    126.980201
Name: 271, dtype: float64, Y좌표     37.616396
X좌표    126.975744
Name: 273, dtype: float64, Y좌표     37.576558
X좌표    126.997449
Name: 274, dtype: float64, Y좌표     37.570102
X좌표    126.990993
Name: 280, dtype: float64, Y좌표     37.570421
X좌표    126.996880
Name: 281, dtype: float64, Y좌표     37.570792
X좌표    127.003206
Name: 282, dtype: float64, Y좌표     37.576484
X좌표    126.967125
Name: 283, dtype: float64, Y좌표     37.576319
X좌표    126.985506
Name: 287, dtype: float64, Y좌표     37.573801
X좌표    126.987750
Name: 290, dtype: float64, Y좌표     37.601242
X좌표    126.955716
Name: 291, dtype: float64, Y좌표     37.570671
X좌표    127.000025
Name: 294, dtype: float64, Y좌표     37.617237
X좌표    126.977047
Name: 295, dtype: float64, Y좌표     37.576767
X좌표    126.967678
Name: 296, dtype: float64, Y좌표     37.575984
X좌표    127.002580
Name: 297, dtype: float64, Y좌표     37.575272
X좌표    126.986981
Name: 298, dtype: float64, Y좌표     37.581027
X좌표    126.966894
Name: 301, dtype: float64, Y좌표     37.616305
X좌표    126.978369
Name: 302, dtype: float64, Y좌표     37.574977
X좌표    127.005405
Name: 304, dtype: float64, Y좌표     37.577173
X좌표    126.986118
Name: 305, dtype: float64, Y좌표     37.615944
X좌표    126.979873
Name: 307, dtype: float64, Y좌표     37.574164
X좌표    126.965859
Name: 308, dtype: float64, Y좌표     37.578791
X좌표    126.985362
Name: 309, dtype: float64, Y좌표     37.587419
X좌표    126.981744
Name: 311, dtype: float64, Y좌표     37.614649
X좌표    126.979494
Name: 313, dtype: float64, Y좌표     37.572618
X좌표    126.961689
Name: 314, dtype: float64, Y좌표     37.574029
X좌표    127.015792
Name: 315, dtype: float64, Y좌표     37.579242
X좌표    126.986635
Name: 316, dtype: float64, Y좌표     37.572152
X좌표    126.961280
Name: 317, dtype: float64, Y좌표     37.612864
X좌표    126.981686
Name: 319, dtype: float64, Y좌표     37.571494
X좌표    126.962337
Name: 320, dtype: float64, Y좌표     37.576037
X좌표    127.015720
Name: 321, dtype: float64, Y좌표     37.579255
X좌표    126.987959
Name: 323, dtype: float64, Y좌표     37.59476
X좌표    126.96386
Name: 324, dtype: float64, Y좌표     37.613047
X좌표    126.979348
Name: 325, dtype: float64, Y좌표     37.571188
X좌표    126.963986
Name: 326, dtype: float64, Y좌표     37.577415
X좌표    127.015561
Name: 327, dtype: float64, Y좌표     37.615262
X좌표    126.978282
Name: 330, dtype: float64, Y좌표     37.569989
X좌표    126.965806
Name: 331, dtype: float64, Y좌표     37.578359
X좌표    127.015505
Name: 332, dtype: float64, Y좌표     37.599563
X좌표    126.959470
Name: 334, dtype: float64, Y좌표     37.613264
X좌표    126.978112
Name: 336, dtype: float64, Y좌표     37.569243
X좌표    126.966825
Name: 337, dtype: float64, Y좌표     37.580323
X좌표    127.015569
Name: 338, dtype: float64, Y좌표     37.583863
X좌표    126.985249
Name: 339, dtype: float64, Y좌표     37.611008
X좌표    126.977856
Name: 342, dtype: float64, Y좌표     37.608995
X좌표    126.973334
Name: 347, dtype: float64, Y좌표     37.589152
X좌표    126.989734
Name: 351, dtype: float64, Y좌표     37.604887
X좌표    126.960786
Name: 363, dtype: float64, Y좌표     37.583463
X좌표    127.001456
Name: 365, dtype: float64, Y좌표     37.578697
X좌표    127.001993
Name: 366, dtype: float64, Y좌표     37.577602
X좌표    126.997774
Name: 371, dtype: float64, Y좌표     37.573641
X좌표    127.002209
Name: 368, dtype: float64, Y좌표     37.578951
X좌표    126.998157
Name: 373, dtype: float64, Y좌표     37.571594
X좌표    126.983243
Name: 374, dtype: float64, Y좌표     37.575710
X좌표    126.984083
Name: 376, dtype: float64, Y좌표     37.573032
X좌표    126.983156
Name: 377, dtype: float64, Y좌표     37.564985
X좌표    126.987530
Name: 379, dtype: float64, Y좌표     37.564350
X좌표    126.987852
Name: 380, dtype: float64, Y좌표     37.555484
X좌표    126.973116
Name: 385, dtype: float64, Y좌표     37.557960
X좌표    126.973698
Name: 405, dtype: float64, Y좌표     37.551619
X좌표    126.962263
Name: 5697, dtype: float64, Y좌표     37.554446
X좌표    126.966234
Name: 388, dtype: float64, Y좌표     37.556552
X좌표    126.967939
Name: 389, dtype: float64, Y좌표     37.555836
X좌표    126.969248
Name: 545, dtype: float64, Y좌표     37.559513
X좌표    126.964481
Name: 393, dtype: float64, Y좌표     37.560933
X좌표    126.967953
Name: 546, dtype: float64, Y좌표     37.562476
X좌표    126.969224
Name: 4892, dtype: float64, Y좌표     37.562404
X좌표    127.006784
Name: 397, dtype: float64, Y좌표     37.564906
X좌표    126.967787
Name: 398, dtype: float64, Y좌표     37.559752
X좌표    126.970992
Name: 543, dtype: float64, Y좌표     37.558771
X좌표    126.973738
Name: 401, dtype: float64, Y좌표     37.553342
X좌표    126.976082
Name: 402, dtype: float64, Y좌표     37.558613
X좌표    126.976205
Name: 406, dtype: float64, Y좌표     37.558558
X좌표    126.975672
Name: 407, dtype: float64, Y좌표     37.560967
X좌표    126.978731
Name: 568, dtype: float64, Y좌표     37.561175
X좌표    126.977920
Name: 409, dtype: float64, Y좌표     37.562763
X좌표    126.976143
Name: 412, dtype: float64, Y좌표     37.562052
X좌표    126.975908
Name: 411, dtype: float64, Y좌표     37.563675
X좌표    126.975340
Name: 414, dtype: float64, Y좌표     37.568363
X좌표    126.977365
Name: 415, dtype: float64, Y좌표     37.567519
X좌표    126.982929
Name: 416, dtype: float64, Y좌표     37.490428
X좌표    126.924483
Name: 8929, dtype: float64, Y좌표     37.562891
X좌표    126.981548
Name: 418, dtype: float64, Y좌표     37.562885
X좌표    126.982008
Name: 419, dtype: float64, Y좌표     37.560764
X좌표    126.981512
Name: 420, dtype: float64, Y좌표     37.558492
X좌표    126.978465
Name: 422, dtype: float64, Y좌표     37.559462
X좌표    126.982719
Name: 424, dtype: float64, Y좌표     37.560654
X좌표    126.985241
Name: 425, dtype: float64, Y좌표     37.560893
X좌표    126.984491
Name: 426, dtype: float64, Y좌표     37.560872
X좌표    126.992484
Name: 428, dtype: float64, Y좌표     37.561223
X좌표    126.994918
Name: 429, dtype: float64, Y좌표     37.561918
X좌표    126.996558
Name: 430, dtype: float64, Y좌표     37.563346
X좌표    126.993112
Name: 431, dtype: float64, Y좌표     37.565876
X좌표    126.985390
Name: 432, dtype: float64, Y좌표     37.566138
X좌표    126.981171
Name: 433, dtype: float64, Y좌표     37.566246
X좌표    126.986523
Name: 434, dtype: float64, Y좌표     37.566009
X좌표    126.988828
Name: 435, dtype: float64, Y좌표     37.566121
X좌표    126.991328
Name: 437, dtype: float64, Y좌표     37.566647
X좌표    126.996218

In [ ]:
for i in range(busUser_info.shape[0]):

    if busUser_info['bus_sta_nm'].iloc[i] in list(stopName_XY.keys()):
        
        busUser_info['lati'].iloc[i]=stopName_XY[busUser_info['bus_sta_nm'].iloc[i]]['Y좌표']
        busUser_info['long'].iloc[i]=stopName_XY[busUser_info['bus_sta_nm'].iloc[i]]['X좌표']
    
        
#         print(stopName_XY[busUser_info['bus_sta_nm'].iloc[i]]['Y좌표'])
#         print(stopName_XY[busUser_info['bus_sta_nm'].iloc[i]]['X좌표'])

C:\Users\B-17\AppData\Roaming\Python\Python36\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\B-17\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\B-17\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [ ]:
for i in range(busUser_info.shape[0]):
    if len(busStop[busStop['정류소명']==busUser_info.iloc[i]['bus_sta_nm']]['Y좌표']) > 0 :  
        busUser_info['lati'].iloc[i]=busStop[busStop['정류소명']== busUser_info.iloc[i]['bus_sta_nm']]['Y좌표'].iloc[0]
        #print(busStop[busStop['정류소명']== busUser_info.iloc[i]['bus_sta_nm']]['Y좌표'].iloc[0])
    else: # 위치 정보 없을때
        busUser_info['lati'].iloc[i]= 0
        
    if len(busStop[busStop['정류소명']==busUser_info.iloc[i]['bus_sta_nm']]['X좌표']) > 0:
        busUser_info['long'].iloc[i]=busStop[busStop['정류소명']== busUser_info.iloc[i]['bus_sta_nm']]['X좌표'].iloc[0]
        #print(busStop[busStop['정류소명']== busUser_info.iloc[i]['bus_sta_nm']]['X좌표'].iloc[0])
    else: # 위치 정보 없을때
        busUser_info['long'].iloc[i] = 0

In [45]:
busUser_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 361024 entries, 0 to 361023
Data columns (total 6 columns):
alight_pasgr_num    361024 non-null int64
bus_sta_nm          361024 non-null object
ride_pasgr_num      361024 non-null int64
use_dt              361024 non-null int64
lati                361024 non-null int64
long                361024 non-null int64
dtypes: int64(5), object(1)
memory usage: 16.5+ MB

In [46]:
busUser_info.isnull().sum()

alight_pasgr_num    0
bus_sta_nm          0
ride_pasgr_num      0
use_dt              0
lati                0
long                0
dtype: int64

In [57]:
busUser_info

,alight_pasgr_num,bus_sta_nm,ride_pasgr_num,use_dt,lati,long
0,114,명륜3가.성대입구,74,20180101,1000,0
1,31,을지로입구.로얄호텔,105,20180101,0,0
2,27,을지로2가.파인에빈뉴,57,20180101,0,0
3,7,서빙고역교차로,8,20180101,0,0
4,83,을지로3가,20,20180101,0,0
5,16,을지로3가,26,20180101,0,0
6,63,을지로4가,14,20180101,0,0
7,65,원남동,27,20180101,0,0
8,13,을지로5가.중부시장,10,20180101,0,0
9,39,을지로6가.국립중앙의료원,49,20180101,0,0
10,0,서울시립북서울미술관,18,20180101,0,0
11,37,월곡뉴타운,97,20180101,0,0
12,22,중계시영3단지상가,145,20180101,0,0
13,13,중계시영4단지,97,20180101,0,0
14,23,하계우성아파트,243,20180101,0,0
15,20,하계극동아파트,118,20180101,0,0
16,39,월계헬스케어센터,98,20180101,0,0
17,131,월계헬스케어센터,53,20180101,0,0
18,175,하계시영아파트,27,20180101,0,0
19,99,하계현대아파트,6,20180101,0,0
20,75,노원구민체육센터,21,20180101,0,0
21,113,삼선교.한성대학교,62,20180101,0,0
22,48,창경궁.서울대학교병원,22,20180101,0,0
23,77,삼선교.한성대학교,182,20180101,0,0
24,12,중계역,0,20180101,0,0
25,1,중계역,15,20180101,0,0
26,0,노원평생학습관,11,20180101,0,0
27,8,중계역2번출구,55,20180101,0,0
28,17,중계3단지목련아파트,45,20180101,0,0
29,7,노원경찰서,139,20180101,0,0
...,...,...,...,...,...,...
360994,121,서울중부기술교육원.블루스퀘어,92,20181231,0,0
360995,112,순천향대학병원,561,20181231,0,0
360996,320,한남5거리,178,20181231,0,0
360997,170,신당동.청구역,224,20181231,0,0
360998,239,신당동.청구역,152,20181231,0,0
360999,239,약수역2번출구.중구구립도서관,157,20181231,0,0
361000,179,약수역3번출구.약수하이츠,358,20181231,0,0
361001,74,장충단로입구,17,20181231,0,0
361002,147,신사역,310,20181231,0,0
361003,561,순천향대학병원.한남오거리,468,20181231,0,0
361004,109,송도병원앞,92,20181231,0,0
361005,256,명륜3가.성대입구,385,20181231,0,0
361006,238,정릉길음시장,848,20181231,0,0
361007,283,원남동,228,20181231,0,0
361008,9,정릉산장아파트,850,20181231,0,0
361009,81,정릉4동주민센터.경국사,183,20181231,0,0
361010,151,정릉4동주민센터.경국사,9,20181231,0,0
361011,449,뉴코아아울렛,592,20181231,0,0
361012,380,신반포자이아파트,399,20181231,0,0
361013,112,KEB하나은행정릉중앙지점,437,20181231,0,0
361014,260,KEB하나은행정릉중앙지점,62,20181231,0,0
361015,150,정릉우체국앞,558,20181231,0,0
361016,291,숭덕초교,145,20181231,0,0
361017,208,영동교입구.청담자이아파트,167,20181231,0,0
361018,146,우리은행청담지점.청담삼익아파트,202,20181231,0,0
361019,236,은마파출소,795,20181231,0,0
361020,663,휘문중고등학교,215,20181231,0,0
361021,295,삼성역,752,20181231,0,0
361022,106,시립개포도서관,1,20181231,0,0
361023,181,신반포13차아파트,161,20181231,0,0

In [48]:
 busUser_info['lati' ].value_counts()

0    361024
Name: lati, dtype: int64